source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'mysql2','~>0.3.11'
gem 'jquery-rails','~>2.2.1'
gem 'jquery-ui-rails','~>4.0.2'
gem 'hirb','~>0.7.1'
gem 'interactive_editor','~>0.0.10'
gem 'will_paginate', '~> 3.0'
gem 'bcrypt-ruby', '~>3.0.1',:require => 'bcrypt'
